---

- name: Add nginx conf.d
  template:
    src: default.conf
    dest: /etc/nginx/conf.d
    mode: 0755
  notify: Restart nginx
  become: yes

- name: Add nginx production config
  copy:
    src: nginx.conf
    dest: /etc/nginx
    mode: 0700
  notify: Restart nginx
  become: yes

- name: Create /var/nginx dir
  file:
    path: /var/nginx
    state: directory
    mode: '0755'
  become: yes

- name: Create dir for storing temporary request bodies
  file:
    path: /var/nginx/client_body_temp
    state: directory
    mode: '0755'
  become: yes

- name: Check log dir
  file:
    path: /var/log/nginx
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id }}"
  become: yes

- name: Create access.log
  file:
    path: /var/log/nginx/access.log
    state: touch
    mode: '0755'
    owner: "{{ ansible_user_id }}"
  become: yes

- name: Ensure that nginx service is active
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: Permit traffic in default zone for service
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
  become: yes

- name: Add IP address of host to hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ nginx_host_ip }} {{ nginx_domain }}"
    state: present
  become: yes

