---
# removing and installing epel-release for preventing NO PACKAGE NGINX AVAILABLE error
- name: Remove epel-release
  yum:
    name: epel-release
    state: absent
  become: yes

- name: Install epel-release
  yum:
    name: epel-release
    state: present
  become: yes

- name: Install nginx
  yum:
    name: nginx
    state: present
  become: yes
