---
- name: working with centOs
  hosts: servers
  pre_tasks:
  - name: Include dev tools vars
    include_vars: vars.yml
  - name: Install Development tools
    yum:
      name: "{{ dev_tools_packages }}"
      state: present
    become: yes
  - name: Get openssl version
    command: openssl version
    register: openssl_output
    ignore_errors: yes
  - name: Set openssl version fact
    set_fact:
      openssl_version: '{{ openssl_output.stdout.split(" ")[1][:3] | default(0) }}'
  - name: Setup OpenSSL 1.1.1
    import_tasks: 'openssl.yml'
    when: openssl_version != "1.1"
  roles:
    - role: '../roles/postgres'
    - role: '../roles/nginx'
    - role: '../roles/docker'
  tasks:
  - name: Copy project files
    copy:
      src: ../files/web
      dest: /var/www/sre
      owner: root
      group: root
      mode: '1755'
    become: yes
