---
- name: working with centOs
  hosts: servers
  tasks:
  - name: Copy project files
    copy:
      src: ../files/web
      dest: /var/www/sre
      owner: root
      group: root
      mode: '1755'
    become: yes
    register: changed_output
  - name: docker-compose down
    command:
      chdir: /var/www/sre
      cmd: docker-compose down
    become: yes
    when: "{{ changed_output.changed }}"
  - name: docker-compose build
    command:
      chdir: /var/www/sre
      cmd: docker-compose build
    become: yes
    when: "{{ changed_output.changed }}"
  - name: docker-compose up -d
    command:
      chdir: /var/www/sre
      cmd: docker-compose up -d
    become: yes
    when: "{{ changed_output.changed }}"
