---
- name: Install and build web
  hosts: servers
  pre_tasks:
    - include_vars: app_vars/web.yml
  roles:
    - nginx.install
    - nginx.configure
    - docker.install
    - postgresql.install
    - postgresql.configure.user
    - postgresql.configure.prod
    - postgresql.add-database-and-tables
    - services/web/roles/build