---

postgres_data_dir: "/var/lib/pgsql/14/data"
postgres_bin_path: "/usr/pgsql-14/bin"
postgres_user: postgres
postgres_password: postgres
postgres_db_name: sre_intaro
postgres_db_tables:
  - name: author
    columns:
    - id bigserial primary key
    - name varchar
postgres_production_settings:
  - name: max_connections
    value: '200'
  - name: shared_buffers
    value: '163584kB'
  - name: effective_cache_size
    value: '490752kB'
  - name: maintenance_work_mem
    value: '40896kB'
  - name: checkpoint_completion_target
    value: '0.9'
  - name: wal_buffers
    value: '4907kB'
  - name: default_statistics_target
    value: '100'
  - name: random_page_cost
    value: '4'
  - name: effective_io_concurrency
    value: '2'
  - name: work_mem
    value: '408kB'
  - name: min_wal_size
    value: '1GB'
  - name: max_wal_size
    value: '4GB'
  - name: max_worker_processes
    value: '4'
  - name: max_parallel_workers_per_gather
    value: '2'
  - name: max_parallel_workers
    value: '4'
  - name: max_parallel_maintenance_workers
    value: '2'
