---

- name: Wget source code
  get_url:
    url: https://www.python.org/ftp/python/3.11.2/Python-3.11.2.tgz
    dest: /tmp
    validate_certs: false
  become: yes

- name: Extract downloaded file
  unarchive:
    src: /tmp/Python-3.11.2.tgz
    dest: /tmp
    remote_src: yes
  become: yes

- name: Configure Python
  command:
    cmd:  ./configure --with-openssl=/usr/local/openssl
    chdir: /tmp/Python-3.11.2
  become: yes

- name: Build Python
  command:
    cmd: make
    chdir: /tmp/Python-3.11.2
  become: yes

- name: Install Python
  make:
    chdir: /tmp/Python-3.11.2
    target: altinstall
  become: yes

- name: Add /usr/local/bin to PATH
  copy:
    src: ../files/python.sh
    dest: /etc/profile.d
    mode: 0644
  become: yes
