- name: Create postgres user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_password }}"
- name: Ensure we have access from the new user
  become: true
  become_user: postgres
  community.postgresql.postgresql_privs:
    db: "{{ postgres_db_name }}"
    role: "{{ postgres_user }}"
    objs: ALL_IN_SCHEMA
    privs: SELECT,INSERT,UPDATE,DELETE
