---
- name: Create a new database
  community.postgresql.postgresql_db:
    name: "{{ postgres_db_name }}"
    encoding: UTF-8
  become: true
  become_user: "{{ postgres_user }}"

- name: Ensure we have access from the user
  become: true
  become_user: postgres
  community.postgresql.postgresql_privs:
    db: "{{ postgres_db_name }}"
    role: "{{ postgres_user }}"
    objs: ALL_IN_SCHEMA
    privs: SELECT,INSERT,UPDATE,DELETE

- name: Create table
  community.postgresql.postgresql_table:
    db: "{{ postgres_db_name }}"
    table: "{{ item.name }}"
  with_items:
    - "{{ postgres_db_tables }}"
  become: true
  become_user: "{{ postgres_user }}"

- name: Add columns to tables
  command: psql -U "{{ postgres_user }}" "{{ postgres_db_name }}" -c "ALTER TABLE {{ item.0.name }} ADD COLUMN {{ item.1 }};"
  ignore_errors: true
  with_subelements:
    - "{{ postgres_db_tables }}"
    - columns
  become: true
  become_user: "{{ postgres_user }}"